#!/bin/bash
#########################################################################
# File Name: git_clone.sh
# Author: WangSen
# Email: wangs_hs@163.com
# Created Time: 2017年05月26日 星期五 15时25分54秒
#########################################################################

fetch_url=ssh://wb20174643@192.168.132.189:29418
revision=master_D2A

project_list_device=(
"device/common msm8953_64_N/device/common"
"device/generic/arm64 msm8953_64_N/device/generic/arm64" 
"device/generic/armv7-a-neon msm8953_64_N/device/generic/armv7-a-neon" 
"device/generic/common msm8953_64_N/device/generic/common" 
"device/generic/goldfish msm8953_64_N/device/generic/goldfish" 
"device/generic/mini-emulator-arm64 msm8953_64_N/device/generic/mini-emulator-arm64" 
"device/generic/mini-emulator-armv7-a-neon msm8953_64_N/device/generic/mini-emulator-armv7-a-neon" 
"device/generic/mini-emulator-x86 msm8953_64_N/device/generic/mini-emulator-x86" 
"device/generic/mini-emulator-x86_64 msm8953_64_N/device/generic/mini-emulator-x86_64" 
"device/generic/qemu msm8953_64_N/device/generic/qemu"
"device/generic/x86 msm8953_64_N/device/generic/x86"
"device/generic/x86_64 msm8953_64_N/device/generic/x86_64" 
"device/google/accessory/arduino msm8953_64_N/device/google/accessory/arduino" 
"device/google/accessory/demokit msm8953_64_N/device/google/accessory/demokit" 
"device/google/atv msm8953_64_N/device/google/atv" 
"device/google/contexthub msm8953_64_N/device/google/contexthub" 
"device/qcom/common msm8953_64_N/device/qcom/common"

"device/qcom/sepolicy msm8953_64_N/device/qcom/sepolicy"
"device/sample msm8953_64_N/device/sample"

"device/qcom/msmcobalt msm8953_64_N/platform/vendor/qcom/cobalt" 
"device/qcom/msm8937_32 msm8953_64_N/platform/vendor/qcom/thorium_32" 
"device/qcom/msm8937_64 msm8953_64_N/platform/vendor/qcom/thorium_64" 
"device/qcom/msm8996 msm8953_64_N/platform/vendor/qcom/thulium" 
"device/qcom/msm8953_32 msm8953_64_N/platform/vendor/qcom/titanium_32" 
"device/qcom/msm8953_64 msm8953_64_N/platform/vendor/qcom/titanium_64" 

"device/xiaomi/tiffany msm8953_64_N/platform/device/xiaomi/tiffany"
"device/xiaomi/midolite msm8953_64_N/platform/device/xiaomi/mido_C6_lite"
"device/xiaomi/tissot msm8953_64_N/platform/device/xiaomi/tissot" 
"device/xiaomi/vince msm8953_64_N/platform/device/xiaomi/vince"
"device/xiaomi/vinceb msm8953_64_N/platform/device/xiaomi/vinceb"  

"device/generic/goldfish-opengl msm8953_64_N/device/generic/goldfish-opengl" 
)

project_list_build=(
"build msm8953_64_N/platform/build" 
"build/blueprint msm8953_64_N/platform/build/blueprint" 
"build/kati msm8953_64_N/platform/build/kati" 
"build/soong msm8953_64_N/platform/build/soong" 
)

project_list_external=(
"external/aac msm8953_64_N/platform/external/aac" 
"external/android-clat msm8953_64_N/platform/external/android-clat" 
"external/androidplot msm8953_64_N/platform/external/androidplot" 
"external/ant-glob msm8953_64_N/platform/external/ant-glob" 
"external/ant-wireless/ant_native msm8953_64_N/platform/external/ant-wireless/ant_native" 
"external/ant-wireless/ant_service msm8953_64_N/platform/external/ant-wireless/ant_service" 
"external/antlr msm8953_64_N/platform/external/antlr" 
"external/apache-commons-math msm8953_64_N/platform/external/apache-commons-math" 
"external/apache-harmony msm8953_64_N/platform/external/apache-harmony" 
"external/apache-http msm8953_64_N/platform/external/apache-http" 
"external/apache-xml msm8953_64_N/platform/external/apache-xml" 
"external/archive-patcher msm8953_64_N/platform/external/archive-patcher" 
"external/autotest msm8953_64_N/platform/external/autotest" 
"external/avahi msm8953_64_N/platform/external/avahi" 
"external/bison msm8953_64_N/platform/external/bison" 
"external/blktrace msm8953_64_N/platform/external/blktrace" 
"external/boringssl msm8953_64_N/platform/external/boringssl" 
"external/bouncycastle msm8953_64_N/platform/external/bouncycastle" 
"external/brctl msm8953_64_N/platform/external/brctl" 
"external/bsdiff msm8953_64_N/platform/external/bsdiff" 
"external/bzip2 msm8953_64_N/platform/external/bzip2" 
"external/c-ares msm8953_64_N/platform/external/c-ares" 
"external/caliper msm8953_64_N/platform/external/caliper" 
"external/cblas msm8953_64_N/platform/external/cblas" 
"external/ceres-solver msm8953_64_N/platform/external/ceres-solver" 
"external/chromium-libpac msm8953_64_N/platform/external/chromium-libpac" 
"external/chromium-trace msm8953_64_N/platform/external/chromium-trace" 
"external/chromium-webview msm8953_64_N/platform/external/chromium-webview" 
"external/clang msm8953_64_N/platform/external/clang" 
"external/cmockery msm8953_64_N/platform/external/cmockery" 
"external/compiler-rt msm8953_64_N/platform/external/compiler-rt" 
"external/conscrypt msm8953_64_N/platform/external/conscrypt" 
"external/crcalc msm8953_64_N/platform/external/crcalc" 
"external/cros/system_api msm8953_64_N/platform/external/cros/system_api" 
"external/curl msm8953_64_N/platform/external/curl" 
"external/dagger2 msm8953_64_N/platform/external/dagger2" 
"external/dbus msm8953_64_N/platform/external/dbus" 
"external/dbus-binding-generator msm8953_64_N/platform/external/dbus-binding-generator" 
"external/deqp msm8953_64_N/platform/external/deqp" 
"external/dexmaker msm8953_64_N/platform/external/dexmaker" 
"external/dhcpcd-6.8.2 msm8953_64_N/platform/external/dhcpcd-6.8.2" 
"external/dlmalloc msm8953_64_N/platform/external/dlmalloc" 
"external/dng_sdk msm8953_64_N/platform/external/dng_sdk" 
"external/dnsmasq msm8953_64_N/platform/external/dnsmasq" 
"external/doclava msm8953_64_N/platform/external/doclava" 
"external/donuts msm8953_64_N/platform/external/donuts" 
"external/drm_gralloc msm8953_64_N/platform/external/drm_gralloc" 
"external/drm_hwcomposer msm8953_64_N/platform/external/drm_hwcomposer" 
"external/droiddriver msm8953_64_N/platform/external/droiddriver" 
"external/e2fsprogs msm8953_64_N/platform/external/e2fsprogs" 
"external/e2fsprogs_blocks msm8953_64_N/platform/external/e2fsprogs_custom" 
"external/easymock msm8953_64_N/platform/external/easymock" 
"external/ebtables msm8953_64_N/platform/external/ebtables" 
"external/eclipse-basebuilder msm8953_64_N/platform/external/eclipse-basebuilder" 
"external/eclipse-windowbuilder msm8953_64_N/platform/external/eclipse-windowbuilder" 
"external/eigen msm8953_64_N/platform/external/eigen" 
"external/elfutils msm8953_64_N/platform/external/elfutils" 
"external/emma msm8953_64_N/platform/external/emma" 
"external/esd msm8953_64_N/platform/external/esd" 
"external/expat msm8953_64_N/platform/external/expat" 
"external/eyes-free msm8953_64_N/platform/external/eyes-free" 
"external/f2fs-tools msm8953_64_N/platform/external/f2fs-tools" 
"external/fdlibm msm8953_64_N/platform/external/fdlibm" 
"external/fec msm8953_64_N/platform/external/fec" 
"external/fio msm8953_64_N/platform/external/fio" 
"external/flac msm8953_64_N/platform/external/flac" 
"external/fonttools msm8953_64_N/platform/external/fonttools" 
"external/freetype msm8953_64_N/platform/external/freetype" 
"external/fsck_msdos msm8953_64_N/platform/external/fsck_msdos" 
"external/gemmlowp msm8953_64_N/platform/external/gemmlowp" 
"external/giflib msm8953_64_N/platform/external/giflib" 
"external/glide msm8953_64_N/platform/external/glide" 
"external/gmock msm8953_64_N/platform/external/gmock" 
"external/google-benchmark msm8953_64_N/platform/external/google-benchmark" 
"external/google-breakpad msm8953_64_N/platform/external/google-breakpad" 
"external/google-fonts/carrois-gothic-sc msm8953_64_N/platform/external/google-fonts/carrois-gothic-sc" 
"external/google-fonts/coming-soon msm8953_64_N/platform/external/google-fonts/coming-soon" 
"external/google-fonts/cutive-mono msm8953_64_N/platform/external/google-fonts/cutive-mono" 
"external/google-fonts/dancing-script msm8953_64_N/platform/external/google-fonts/dancing-script" 
"external/google-tv-pairing-protocol msm8953_64_N/platform/external/google-tv-pairing-protocol" 
"external/gptfdisk msm8953_64_N/platform/external/gptfdisk" 
"external/gtest msm8953_64_N/platform/external/gtest" 
"external/guava msm8953_64_N/platform/external/guava" 
"external/guice msm8953_64_N/platform/external/guice" 
"external/hamcrest msm8953_64_N/platform/external/hamcrest" 
"external/harfbuzz_ng msm8953_64_N/platform/external/harfbuzz_ng" 
"external/hyphenation-patterns msm8953_64_N/platform/external/hyphenation-patterns" 
"external/icu msm8953_64_N/platform/external/icu" 
"external/iproute2 msm8953_64_N/platform/external/iproute2" 
"external/ipsec-tools msm8953_64_N/platform/external/ipsec-tools" 
"external/iptables msm8953_64_N/platform/external/iptables" 
"external/iputils msm8953_64_N/platform/external/iputils" 
"external/iw msm8953_64_N/platform/external/iw" 
"external/jacoco msm8953_64_N/platform/external/jacoco" 
"external/jarjar msm8953_64_N/platform/external/jarjar" 
"external/javasqlite msm8953_64_N/platform/external/javasqlite" 
"external/javassist msm8953_64_N/platform/external/javassist" 
"external/jcommander msm8953_64_N/platform/external/jcommander" 
"external/jdiff msm8953_64_N/platform/external/jdiff" 
"external/jemalloc msm8953_64_N/platform/external/jemalloc" 
"external/jetty msm8953_64_N/platform/external/jetty" 
"external/jhead msm8953_64_N/platform/external/jhead" 
"external/jmdns msm8953_64_N/platform/external/jmdns" 
"external/jsilver msm8953_64_N/platform/external/jsilver" 
"external/jsmn msm8953_64_N/platform/external/jsmn" 
"external/json-c msm8953_64_N/platform/external/json-c" 
"external/jsoncpp msm8953_64_N/platform/external/jsoncpp" 
"external/jsr305 msm8953_64_N/platform/external/jsr305" 
"external/jsr330 msm8953_64_N/platform/external/jsr330" 
"external/junit msm8953_64_N/platform/external/junit" 
"external/kernel-headers msm8953_64_N/platform/external/kernel-headers" 
"external/ksoap2 msm8953_64_N/platform/external/ksoap2" 
"external/libavc msm8953_64_N/platform/external/libavc" 
"external/libbrillo msm8953_64_N/platform/external/libbrillo" 
"external/libcap msm8953_64_N/platform/external/libcap" 
"external/libcap-ng msm8953_64_N/platform/external/libcap-ng" 
"external/libchrome msm8953_64_N/platform/external/libchrome" 
"external/libcxx msm8953_64_N/platform/external/libcxx" 
"external/libcxxabi msm8953_64_N/platform/external/libcxxabi" 
"external/libdaemon msm8953_64_N/platform/external/libdaemon" 
"external/libdivsufsort msm8953_64_N/platform/external/libdivsufsort" 
"external/libdrm msm8953_64_N/platform/external/libdrm" 
"external/libedit msm8953_64_N/platform/external/libedit" 
"external/libevent msm8953_64_N/platform/external/libevent" 
"external/libexif msm8953_64_N/platform/external/libexif" 
"external/libgsm msm8953_64_N/platform/external/libgsm" 
"external/libhevc msm8953_64_N/platform/external/libhevc" 
"external/libjpeg-turbo msm8953_64_N/platform/external/libjpeg-turbo" 
"external/liblzf msm8953_64_N/platform/external/liblzf" 
"external/libmicrohttpd msm8953_64_N/platform/external/libmicrohttpd" 
"external/libmpeg2 msm8953_64_N/platform/external/libmpeg2" 
"external/libmtp msm8953_64_N/platform/external/libmtp" 
"external/libnetfilter_conntrack msm8953_64_N/platform/external/libnetfilter_conntrack" 
"external/libnfc-nci msm8953_64_N/platform/external/libnfc-nci" 
"external/libnfc-nxp msm8953_64_N/platform/external/libnfc-nxp" 
"external/libnfnetlink msm8953_64_N/platform/external/libnfnetlink" 
"external/libnl msm8953_64_N/platform/external/libnl" 
"external/libogg msm8953_64_N/platform/external/libogg" 
"external/libopus msm8953_64_N/platform/external/libopus" 
"external/libpcap msm8953_64_N/platform/external/libpcap" 
"external/libphonenumber msm8953_64_N/platform/external/libphonenumber" 
"external/libpng msm8953_64_N/platform/external/libpng" 
"external/libselinux msm8953_64_N/platform/external/libselinux" 
"external/libunwind msm8953_64_N/platform/external/libunwind" 
"external/libunwind_llvm msm8953_64_N/platform/external/libunwind_llvm" 
"external/libusb msm8953_64_N/platform/external/libusb" 
"external/libusb-compat msm8953_64_N/platform/external/libusb-compat" 
"external/libutf msm8953_64_N/platform/external/libutf" 
"external/libvncserver msm8953_64_N/platform/external/libvncserver" 
"external/libvorbis msm8953_64_N/platform/external/libvorbis" 
"external/libvpx msm8953_64_N/platform/external/libvpx" 
"external/libvterm msm8953_64_N/platform/external/libvterm" 
"external/libweave msm8953_64_N/platform/external/libweave" 
"external/libxml2 msm8953_64_N/platform/external/libxml2" 
"external/libyuv msm8953_64_N/platform/external/libyuv" 
"external/littlemock msm8953_64_N/platform/external/littlemock" 
"external/lld msm8953_64_N/platform/external/lld" 
"external/llvm msm8953_64_N/platform/external/llvm" 
"external/ltrace msm8953_64_N/platform/external/ltrace" 
"external/lz4 msm8953_64_N/platform/external/lz4" 
"external/lzma msm8953_64_N/platform/external/lzma" 
"external/markdown msm8953_64_N/platform/external/markdown" 
"external/mdnsresponder msm8953_64_N/platform/external/mdnsresponder" 
"external/mesa3d msm8953_64_N/platform/external/mesa3d" 
"external/messageformat msm8953_64_N/platform/external/messageformat" 
"external/minijail msm8953_64_N/platform/external/minijail" 
"external/mksh msm8953_64_N/platform/external/mksh" 
"external/mm-dash msm8953_64_N/platform/external/mm-dash" 
"external/mmc-utils msm8953_64_N/platform/external/mmc-utils" 
"external/mockftpserver msm8953_64_N/platform/external/mockftpserver" 
"external/mockito msm8953_64_N/platform/external/mockito" 
"external/mockwebserver msm8953_64_N/platform/external/mockwebserver" 
"external/modp_b64 msm8953_64_N/platform/external/modp_b64" 
"external/mp4parser msm8953_64_N/platform/external/mp4parser" 
"external/mtpd msm8953_64_N/platform/external/mtpd" 
"external/nanohttpd msm8953_64_N/platform/external/nanohttpd" 
"external/nanopb-c msm8953_64_N/platform/external/nanopb-c" 
"external/naver-fonts msm8953_64_N/platform/external/naver-fonts" 
"external/netcat msm8953_64_N/platform/external/netcat" 
"external/netperf msm8953_64_N/platform/external/netperf" 
"external/neven msm8953_64_N/platform/external/neven" 
"external/nfacct msm8953_64_N/platform/external/nfacct" 
"external/nist-pkits msm8953_64_N/platform/external/nist-pkits" 
"external/nist-sip msm8953_64_N/platform/external/nist-sip" 
"external/noto-fonts msm8953_64_N/platform/external/noto-fonts" 
"external/oauth msm8953_64_N/platform/external/oauth" 
"external/objenesis msm8953_64_N/platform/external/objenesis" 
"external/okhttp msm8953_64_N/platform/external/okhttp" 
"external/opencv msm8953_64_N/platform/external/opencv" 
"external/opencv3 msm8953_64_N/platform/external/opencv3" 
"external/owasp/sanitizer msm8953_64_N/platform/external/owasp/sanitizer" 
"external/parameter-framework msm8953_64_N/platform/external/parameter-framework" 
"external/pcre msm8953_64_N/platform/external/pcre" 
"external/pdfium msm8953_64_N/platform/external/pdfium" 
"external/piex msm8953_64_N/platform/external/piex" 
"external/powertop msm8953_64_N/platform/external/powertop" 
"external/ppp msm8953_64_N/platform/external/ppp" 
"external/proguard msm8953_64_N/platform/external/proguard" 
"external/protobuf msm8953_64_N/platform/external/protobuf" 
"external/regex-re2 msm8953_64_N/platform/external/regex-re2" 
"external/replicaisland msm8953_64_N/platform/external/replicaisland" 
"external/rmi4utils msm8953_64_N/platform/external/rmi4utils" 
"external/robolectric msm8953_64_N/platform/external/robolectric" 
"external/roboto-fonts msm8953_64_N/platform/external/roboto-fonts" 
"external/rootdev msm8953_64_N/platform/external/rootdev" 
"external/safe-iop msm8953_64_N/platform/external/safe-iop" 
"external/scrypt msm8953_64_N/platform/external/scrypt" 
"external/selinux msm8953_64_N/platform/external/selinux" 
"external/sfntly msm8953_64_N/platform/external/sfntly" 
"external/shflags msm8953_64_N/platform/external/shflags" 
"external/skia msm8953_64_N/platform/external/skia" 
"external/sl4a msm8953_64_N/platform/external/sl4a" 
"external/slf4j msm8953_64_N/platform/external/slf4j" 
"external/smali msm8953_64_N/platform/external/smali" 
"external/snakeyaml msm8953_64_N/platform/external/snakeyaml" 
"external/sonic msm8953_64_N/platform/external/sonic" 
"external/sonivox msm8953_64_N/platform/external/sonivox" 
"external/speex msm8953_64_N/platform/external/speex" 
"external/sqlite msm8953_64_N/platform/external/sqlite" 
"external/squashfs-tools msm8953_64_N/platform/external/squashfs-tools" 
"external/srtp msm8953_64_N/platform/external/srtp" 
"external/strace msm8953_64_N/platform/external/strace" 
"external/svox msm8953_64_N/platform/external/svox" 
"external/tagsoup msm8953_64_N/platform/external/tagsoup" 
"external/tcpdump msm8953_64_N/platform/external/tcpdump" 
"external/testng msm8953_64_N/platform/external/testng" 
"external/timezonepicker-support msm8953_64_N/platform/external/timezonepicker-support" 
"external/tinyalsa msm8953_64_N/platform/external/tinyalsa" 
"external/tinycompress msm8953_64_N/platform/external/tinycompress" 
"external/tinyxml msm8953_64_N/platform/external/tinyxml" 
"external/tinyxml2 msm8953_64_N/platform/external/tinyxml2" 
"external/tlsdate msm8953_64_N/platform/external/tlsdate" 
"external/toybox msm8953_64_N/platform/external/toybox" 
"external/tpm2 msm8953_64_N/platform/external/tpm2" 
"external/tremolo msm8953_64_N/platform/external/tremolo" 
"external/unicode msm8953_64_N/platform/external/unicode" 
"external/v8 msm8953_64_N/platform/external/v8" 
"external/valgrind msm8953_64_N/platform/external/valgrind" 
"external/vboot_reference msm8953_64_N/platform/external/vboot_reference" 
"external/vixl msm8953_64_N/platform/external/vixl" 
"external/vogar msm8953_64_N/platform/external/vogar" 
"external/vulkan-validation-layers msm8953_64_N/platform/external/vulkan-validation-layers" 
"external/webp msm8953_64_N/platform/external/webp" 
"external/webrtc msm8953_64_N/platform/external/webrtc" 
"external/wpa_supplicant_8 msm8953_64_N/platform/external/wpa_supplicant_8" 
"external/xmlrpcpp msm8953_64_N/platform/external/xmlrpcpp" 
"external/xmlwriter msm8953_64_N/platform/external/xmlwriter" 
"external/xmp_toolkit msm8953_64_N/platform/external/xmp_toolkit" 
"external/zlib msm8953_64_N/platform/external/zlib" 
"external/zopfli msm8953_64_N/platform/external/zopfli" 
"external/zxing msm8953_64_N/platform/external/zxing" 

"external/dirac msm8953_64_N/platform/external/dirac" 
"external/ImageMagick msm8953_64_N/platform/external/ImageMagick" 
"external/ims msm8953_64_N/platform/external/ims" 
"external/libgdx msm8953_64_N/platform/external/libgdx" 
"external/universal-tween-engine msm8953_64_N/platform/external/universal-tween-engine" 
)

project_list_frameworks=(
"frameworks/av msm8953_64_N/platform/frameworks/av" 
"frameworks/base msm8953_64_N/platform/frameworks/base" 
"frameworks/compile/libbcc msm8953_64_N/platform/frameworks/compile/libbcc" 
"frameworks/compile/mclinker msm8953_64_N/platform/frameworks/compile/mclinker" 
"frameworks/compile/slang msm8953_64_N/platform/frameworks/compile/slang" 
"frameworks/data-binding msm8953_64_N/platform/frameworks/data-binding" 
"frameworks/ex msm8953_64_N/platform/frameworks/ex" 
"frameworks/minikin msm8953_64_N/platform/frameworks/minikin" 
"frameworks/ml msm8953_64_N/platform/frameworks/ml" 
"frameworks/multidex msm8953_64_N/platform/frameworks/multidex" 
"frameworks/native msm8953_64_N/platform/frameworks/native" 
"frameworks/opt/bitmap msm8953_64_N/platform/frameworks/opt/bitmap" 
"frameworks/opt/bluetooth msm8953_64_N/platform/frameworks/opt/bluetooth" 
"frameworks/opt/calendar msm8953_64_N/platform/frameworks/opt/calendar" 
"frameworks/opt/chips msm8953_64_N/platform/frameworks/opt/chips" 
"frameworks/opt/colorpicker msm8953_64_N/platform/frameworks/opt/colorpicker" 
"frameworks/opt/datetimepicker msm8953_64_N/platform/frameworks/opt/datetimepicker" 
"frameworks/opt/emoji msm8953_64_N/platform/frameworks/opt/emoji" 
"frameworks/opt/inputconnectioncommon msm8953_64_N/platform/frameworks/opt/inputconnectioncommon" 
"frameworks/opt/inputmethodcommon msm8953_64_N/platform/frameworks/opt/inputmethodcommon" 
"frameworks/opt/net/ethernet msm8953_64_N/platform/frameworks/opt/net/ethernet" 
"frameworks/opt/net/ims msm8953_64_N/platform/frameworks/opt/net/ims" 
"frameworks/opt/net/voip msm8953_64_N/platform/frameworks/opt/net/voip" 
"frameworks/opt/net/wifi msm8953_64_N/platform/frameworks/opt/net/wifi" 
"frameworks/opt/photoviewer msm8953_64_N/platform/frameworks/opt/photoviewer" 
"frameworks/opt/setupwizard msm8953_64_N/platform/frameworks/opt/setupwizard" 
"frameworks/opt/telephony msm8953_64_N/platform/frameworks/opt/telephony" 
"frameworks/opt/timezonepicker msm8953_64_N/platform/frameworks/opt/timezonepicker" 
"frameworks/opt/vcard msm8953_64_N/platform/frameworks/opt/vcard" 
"frameworks/rs msm8953_64_N/platform/frameworks/rs" 
"frameworks/support msm8953_64_N/platform/frameworks/support" 
"frameworks/volley msm8953_64_N/platform/frameworks/volley" 
"frameworks/webview msm8953_64_N/platform/frameworks/webview" 
"frameworks/wilhelm msm8953_64_N/platform/frameworks/wilhelm" 
)

project_list_hardware=(
"hardware/akm msm8953_64_N/platform/hardware/akm" 
"hardware/broadcom/libbt msm8953_64_N/platform/hardware/broadcom/libbt" 
"hardware/broadcom/wlan msm8953_64_N/platform/hardware/broadcom/wlan" 
"hardware/google/apf msm8953_64_N/platform/hardware/google/apf" 
"hardware/invensense msm8953_64_N/platform/hardware/invensense" 
"hardware/libhardware msm8953_64_N/platform/hardware/libhardware" 
"hardware/libhardware_legacy msm8953_64_N/platform/hardware/libhardware_legacy" 
"hardware/qcom/audio msm8953_64_N/platform/hardware/qcom/audio" 
"hardware/qcom/bootctrl msm8953_64_N/platform/hardware/qcom/bootctrl" 
"hardware/qcom/bt msm8953_64_N/platform/hardware/qcom/bt" 
"hardware/qcom/camera msm8953_64_N/platform/hardware/qcom/camera" 
"hardware/qcom/display msm8953_64_N/platform/hardware/qcom/display" 
"hardware/qcom/gps msm8953_64_N/platform/hardware/qcom/gps" 
"hardware/qcom/media msm8953_64_N/platform/hardware/qcom/media" 
"hardware/qcom/wlan msm8953_64_N/platform/hardware/qcom/wlan" 
"hardware/ril msm8953_64_N/platform/hardware/ril" 
)

project_list_packages=(
"packages/apps/BasicSmsReceiver msm8953_64_N/platform/packages/apps/BasicSmsReceiver" 
"packages/apps/Bluetooth msm8953_64_N/platform/packages/apps/Bluetooth" 
"packages/apps/Browser2 msm8953_64_N/platform/packages/apps/Browser2" 
"packages/apps/CMFileManager msm8953_64_N/platform/packages/apps/CMFileManager" 
"packages/apps/Calculator msm8953_64_N/platform/packages/apps/Calculator" 
"packages/apps/Calendar msm8953_64_N/platform/packages/apps/Calendar" 
"packages/apps/Camera msm8953_64_N/platform/packages/apps/Camera" 
"packages/apps/Camera2 msm8953_64_N/platform/packages/apps/Camera2" 
"packages/apps/CarrierConfig msm8953_64_N/platform/packages/apps/CarrierConfig" 
"packages/apps/CellBroadcastReceiver msm8953_64_N/platform/packages/apps/CellBroadcastReceiver" 
"packages/apps/CertInstaller msm8953_64_N/platform/packages/apps/CertInstaller" 
"packages/apps/Contacts msm8953_64_N/platform/packages/apps/Contacts" 
"packages/apps/ContactsCommon msm8953_64_N/platform/packages/apps/ContactsCommon" 
"packages/apps/DeskClock msm8953_64_N/platform/packages/apps/DeskClock" 
"packages/apps/DevCamera msm8953_64_N/platform/packages/apps/DevCamera" 
"packages/apps/Dialer msm8953_64_N/platform/packages/apps/Dialer" 
"packages/apps/Email msm8953_64_N/platform/packages/apps/Email" 
"packages/apps/EmergencyInfo msm8953_64_N/platform/packages/apps/EmergencyInfo" 
"packages/apps/ExactCalculator msm8953_64_N/platform/packages/apps/ExactCalculator" 
"packages/apps/Exchange msm8953_64_N/platform/packages/apps/Exchange" 
"packages/apps/FMRadio msm8953_64_N/platform/packages/apps/FMRadio" 
"packages/apps/Gallery msm8953_64_N/platform/packages/apps/Gallery" 
"packages/apps/Gallery2 msm8953_64_N/platform/packages/apps/Gallery2" 
"packages/apps/HTMLViewer msm8953_64_N/platform/packages/apps/HTMLViewer" 
"packages/apps/KeyChain msm8953_64_N/platform/packages/apps/KeyChain" 
"packages/apps/Launcher2 msm8953_64_N/platform/packages/apps/Launcher2" 
"packages/apps/Launcher3 msm8953_64_N/platform/packages/apps/Launcher3" 
"packages/apps/LegacyCamera msm8953_64_N/platform/packages/apps/LegacyCamera" 
"packages/apps/ManagedProvisioning msm8953_64_N/platform/packages/apps/ManagedProvisioning" 
"packages/apps/Messaging msm8953_64_N/platform/packages/apps/Messaging" 
"packages/apps/Mms msm8953_64_N/platform/packages/apps/Mms" 
"packages/apps/Music msm8953_64_N/platform/packages/apps/Music" 
"packages/apps/MusicFX msm8953_64_N/platform/packages/apps/MusicFX" 
"packages/apps/Nfc msm8953_64_N/platform/packages/apps/Nfc" 
"packages/apps/OneTimeInitializer msm8953_64_N/platform/packages/apps/OneTimeInitializer" 
"packages/apps/PackageInstaller msm8953_64_N/platform/packages/apps/PackageInstaller" 
"packages/apps/Phone msm8953_64_N/platform/packages/apps/Phone" 
"packages/apps/PhoneCommon msm8953_64_N/platform/packages/apps/PhoneCommon" 
"packages/apps/Protips msm8953_64_N/platform/packages/apps/Protips" 
"packages/apps/Provision msm8953_64_N/platform/packages/apps/Provision" 
"packages/apps/QuickSearchBox msm8953_64_N/platform/packages/apps/QuickSearchBox" 
"packages/apps/Settings msm8953_64_N/platform/packages/apps/Settings" 
"packages/apps/SmartCardService msm8953_64_N/platform/packages/apps/SmartCardService" 
"packages/apps/SnapdragonCamera msm8953_64_N/platform/packages/apps/SnapdragonCamera" 
"packages/apps/SnapdragonGallery msm8953_64_N/platform/packages/apps/SnapdragonGallery" 
"packages/apps/SnapdragonLauncher msm8953_64_N/platform/packages/apps/SnapdragonLauncher" 
"packages/apps/SnapdragonMusic msm8953_64_N/platform/packages/apps/SnapdragonMusic" 
"packages/apps/SoundRecorder msm8953_64_N/platform/packages/apps/SoundRecorder" 
"packages/apps/SpareParts msm8953_64_N/platform/packages/apps/SpareParts" 
"packages/apps/SpeechRecorder msm8953_64_N/platform/packages/apps/SpeechRecorder" 
"packages/apps/Stk msm8953_64_N/platform/packages/apps/Stk" 
"packages/apps/TV msm8953_64_N/platform/packages/apps/TV" 
"packages/apps/Tag msm8953_64_N/platform/packages/apps/Tag" 
"packages/apps/Terminal msm8953_64_N/platform/packages/apps/Terminal" 
"packages/apps/Test/connectivity msm8953_64_N/platform/packages/apps/Test/connectivity" 
"packages/apps/TvSettings msm8953_64_N/platform/packages/apps/TvSettings" 
"packages/apps/UnifiedEmail msm8953_64_N/platform/packages/apps/UnifiedEmail" 
"packages/experimental msm8953_64_N/platform/packages/experimental" 
"packages/inputmethods/LatinIME msm8953_64_N/platform/packages/inputmethods/LatinIME" 
"packages/inputmethods/OpenWnn msm8953_64_N/platform/packages/inputmethods/OpenWnn" 
"packages/providers/ApplicationsProvider msm8953_64_N/platform/packages/providers/ApplicationsProvider" 
"packages/providers/BlockedNumberProvider msm8953_64_N/platform/packages/providers/BlockedNumberProvider" 
"packages/providers/BookmarkProvider msm8953_64_N/platform/packages/providers/BookmarkProvider" 
"packages/providers/CalendarProvider msm8953_64_N/platform/packages/providers/CalendarProvider" 
"packages/providers/CallLogProvider msm8953_64_N/platform/packages/providers/CallLogProvider" 
"packages/providers/ContactsProvider msm8953_64_N/platform/packages/providers/ContactsProvider" 
"packages/providers/DownloadProvider msm8953_64_N/platform/packages/providers/DownloadProvider" 
"packages/providers/MediaProvider msm8953_64_N/platform/packages/providers/MediaProvider" 
"packages/providers/PartnerBookmarksProvider msm8953_64_N/platform/packages/providers/PartnerBookmarksProvider" 
"packages/providers/TelephonyProvider msm8953_64_N/platform/packages/providers/TelephonyProvider" 
"packages/providers/TvProvider msm8953_64_N/platform/packages/providers/TvProvider" 
"packages/providers/UserDictionaryProvider msm8953_64_N/platform/packages/providers/UserDictionaryProvider" 
"packages/screensavers/Basic msm8953_64_N/platform/packages/screensavers/Basic" 
"packages/screensavers/PhotoTable msm8953_64_N/platform/packages/screensavers/PhotoTable" 
"packages/screensavers/WebView msm8953_64_N/platform/packages/screensavers/WebView" 
"packages/services/Car msm8953_64_N/platform/packages/services/Car" 
"packages/services/Mms msm8953_64_N/platform/packages/services/Mms" 
"packages/services/Telecomm msm8953_64_N/platform/packages/services/Telecomm" 
"packages/services/Telephony msm8953_64_N/platform/packages/services/Telephony" 
"packages/wallpapers/LivePicker msm8953_64_N/platform/packages/wallpapers/LivePicker" 
)

project_list_prebuilts=(
"prebuilts/android-emulator msm8953_64_N/platform/prebuilts/android-emulator" 
"prebuilts/clang/host/linux-x86 msm8953_64_N/platform/prebuilts/clang/host/linux-x86" 
"prebuilts/clang/linux-x86/host/3.6 msm8953_64_N/platform/prebuilts/clang/linux-x86/host/3.6" 
"prebuilts/deqp msm8953_64_N/platform/prebuilts/deqp" 
"prebuilts/devtools msm8953_64_N/platform/prebuilts/devtools" 
"prebuilts/eclipse msm8953_64_N/platform/prebuilts/eclipse" 
"prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 msm8953_64_N/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9" 
"prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 msm8953_64_N/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8" 
"prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 msm8953_64_N/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9" 
"prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.8 msm8953_64_N/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.11-4.8" 
"prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8 msm8953_64_N/platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.15-4.8" 
"prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8 msm8953_64_N/platform/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8" 
"prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9 msm8953_64_N/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9" 
"prebuilts/gdb/linux-x86 msm8953_64_N/platform/prebuilts/gdb/linux-x86" 
"prebuilts/go/linux-x86 msm8953_64_N/platform/prebuilts/go/linux-x86" 
"prebuilts/gradle-plugin msm8953_64_N/platform/prebuilts/gradle-plugin" 
"prebuilts/libs/libedit msm8953_64_N/platform/prebuilts/libs/libedit" 
"prebuilts/maven_repo/android msm8953_64_N/platform/prebuilts/maven_repo/android" 
"prebuilts/misc msm8953_64_N/platform/prebuilts/misc" 
"prebuilts/ndk msm8953_64_N/platform/prebuilts/ndk" 
"prebuilts/ninja/linux-x86 msm8953_64_N/platform/prebuilts/ninja/linux-x86" 
"prebuilts/python/linux-x86/2.7.5 msm8953_64_N/platform/prebuilts/python/linux-x86/2.7.5" 
"prebuilts/qemu-kernel msm8953_64_N/platform/prebuilts/qemu-kernel" 
"prebuilts/sdk msm8953_64_N/platform/prebuilts/sdk" 
"prebuilts/tools msm8953_64_N/platform/prebuilts/tools" 

"prebuilts/gcc/darwin-x86/arm/arm-eabi-4.8 msm8953_64_N/platform/prebuilts/gcc/darwin-x86/arm/arm-eabi-4.8" 
)

project_list_system=(
"system/bt msm8953_64_N/platform/system/bt" 
"system/ca-certificates msm8953_64_N/platform/system/ca-certificates" 
"system/connectivity/apmanager msm8953_64_N/platform/system/connectivity/apmanager" 
"system/connectivity/dhcp_client msm8953_64_N/platform/system/connectivity/dhcp_client" 
"system/connectivity/shill msm8953_64_N/platform/system/connectivity/shill" 
"system/core msm8953_64_N/platform/system/core" 
"system/extras msm8953_64_N/platform/system/extras" 
"system/firewalld msm8953_64_N/platform/system/firewalld" 
"system/gatekeeper msm8953_64_N/platform/system/gatekeeper" 
"system/keymaster msm8953_64_N/platform/system/keymaster" 
"system/media msm8953_64_N/platform/system/media" 
"system/nativepower msm8953_64_N/platform/system/nativepower" 
"system/netd msm8953_64_N/platform/system/netd" 
"system/nvram msm8953_64_N/platform/system/nvram" 
"vendor/qcom/opensource/softap msm8953_64_N/platform/system/qcom" 
"system/security msm8953_64_N/platform/system/security" 
"system/sepolicy msm8953_64_N/platform/system/sepolicy" 
"system/tools/aidl msm8953_64_N/platform/system/tools/aidl" 
"system/tpm msm8953_64_N/platform/system/tpm" 
"system/update_engine msm8953_64_N/platform/system/update_engine" 
"system/vold msm8953_64_N/platform/system/vold" 
"system/weaved msm8953_64_N/platform/system/weaved" 
"system/webservd msm8953_64_N/platform/system/webservd" 
)

project_list_vendor=(
"vendor/codeaurora/telephony msm8953_64_N/platform/vendor/codeaurora/telephony" 
"vendor/nxp/opensource/external/libnfc-nci msm8953_64_N/platform/vendor/nxp/opensource/external/libnfc-nci" 
"vendor/nxp/opensource/frameworks msm8953_64_N/platform/vendor/nxp/opensource/frameworks" 
"vendor/nxp/opensource/packages/apps/Nfc msm8953_64_N/platform/vendor/nxp/opensource/packages/apps/Nfc" 
"vendor/qcom/opensource/bluetooth msm8953_64_N/platform/vendor/qcom-opensource/bluetooth" 
"vendor/qcom/opensource/data-ipa-cfg-mgr msm8953_64_N/platform/vendor/qcom-opensource/data-ipa-cfg-mgr" 
"vendor/qcom/opensource/dataservices msm8953_64_N/platform/vendor/qcom-opensource/dataservices" 
"vendor/qcom/opensource/dpm msm8953_64_N/platform/vendor/qcom-opensource/dpm" 
"vendor/qcom/opensource/fm msm8953_64_N/platform/vendor/qcom-opensource/fm" 
"vendor/qcom/opensource/fst-manager msm8953_64_N/platform/vendor/qcom-opensource/fst-manager" 
"vendor/qcom/opensource/kernel-tests msm8953_64_N/platform/vendor/qcom-opensource/kernel/kernel-tests" 
"vendor/qcom/opensource/location msm8953_64_N/platform/vendor/qcom-opensource/location" 
"vendor/qcom/opensource/mmc-utils msm8953_64_N/platform/vendor/qcom-opensource/mmc-utils" 
"vendor/qcom/opensource/rcs-service msm8953_64_N/platform/vendor/qcom-opensource/rcs-service" 
 
"vendor/qcom/opensource/time-services msm8953_64_N/platform/vendor/qcom-opensource/time-services" 
"vendor/qcom/opensource/tools msm8953_64_N/platform/vendor/qcom-opensource/tools" 
"vendor/qcom/opensource/wlan/prima msm8953_64_N/platform/vendor/qcom-opensource/wlan/prima" 
"vendor/qcom/opensource/wlan/qcacld-2.0 msm8953_64_N/platform/vendor/qcom-opensource/wlan/qcacld-2.0" 
"vendor/qcom/opensource/wlan/utils/sigma-dut msm8953_64_N/platform/vendor/qcom-opensource/wlan/utils/sigma-dut" 

"vendor/qcom/proprietary msm8953_64_N/platform/vendor/qcom/proprietary-msm8953" 
"vendor/qcom/non-hlos-msm8953/ADSP.8953.2.8.2 msm8953_64_N/platform/vendor/qcom/non-hlos/ADSP.8953.2.8.2" 
"vendor/qcom/non-hlos-msm8953/BOOT.BF.3.3 msm8953_64_N/platform/vendor/qcom/non-hlos/BOOT.BF.3.3" 
"vendor/qcom/non-hlos-msm8953/CNSS.PR.4.0 msm8953_64_N/platform/vendor/qcom/non-hlos/CNSS.PR.4.0" 
"vendor/qcom/non-hlos-msm8953/CPE.TSF.1.0 msm8953_64_N/platform/vendor/qcom/non-hlos/CPE.TSF.1.0" 
"vendor/qcom/non-hlos-msm8953/LA.UM.5.6 msm8953_64_N/platform/vendor/qcom/non-hlos/LA.UM.5.6" 

"vendor/qcom/non-hlos-msm8953/MPSS.TA.2.3 msm8953_64_N/platform/vendor/qcom/non-hlos/MPSS.TA.2.3" 
"vendor/qcom/non-hlos-msm8953/MSM8953.LA.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8953.LA.2.0" 
"vendor/qcom/non-hlos-msm8953/RPM.BF.2.4 msm8953_64_N/platform/vendor/qcom/non-hlos/RPM.BF.2.4" 
"vendor/qcom/non-hlos-msm8953/TZ.BF.4.0.5 msm8953_64_N/platform/vendor/qcom/non-hlos/TZ.BF.4.0.5" 
"vendor/qcom/non-hlos-msm8953/VIDEO.VE.4.2 msm8953_64_N/platform/vendor/qcom/non-hlos/VIDEO.VE.4.2" 
"vendor/qcom/non-hlos-msm8953/VIDEO.VE_ULT.3.1 msm8953_64_N/platform/vendor/qcom/non-hlos/VIDEO.VE_ULT.3.1" 

"vendor/qcom/non-hlos-msm8953/SDM450.LA.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/SDM450.LA.2.0" 
"vendor/qcom/non-hlos-msm8953/hq_build msm8953_64_N/platform/vendor/qcom/non-hlos/hq_build" 
"vendor/qcom/non-hlos-msm8953/qcom_tools msm8953_64_N/platform/vendor/qcom/non-hlos/qcom_tools" 
 
"vendor/xiaomi msm8953_64/platform/vendor/xiaomi" 

"vendor/huaqin/tiffany msm8953_64_N/platform/vendor/huaqin/tiffany" 
 
"vendor/qcom/non-hlos-msm8953/ADSP.8953.2.8.2_midolite msm8953_64_N/platform/vendor/qcom/non-hlos/ADSP.8953.2.8.2_midolite" 
"vendor/qcom/non-hlos-msm8953/ADSP.8953.2.8.2_vince msm8953_64_N/platform/vendor/qcom/non-hlos/ADSP.8953.2.8.2_vince" 
)

project_list_others=(
"bootable/bootloader/lk msm8953_64_N/kernel/lk" 
"kernel/msm-3.18 msm8953_64_N/kernel/msm-3.18" 
"abi/cpp msm8953_64_N/platform/abi/cpp" 
"art msm8953_64_N/platform/art" 
"bionic msm8953_64_N/platform/bionic" 
"bootable/recovery msm8953_64_N/platform/bootable/recovery" 

"cts msm8953_64_N/platform/cts" 
"dalvik msm8953_64_N/platform/dalvik" 
"developers/build msm8953_64_N/platform/developers/build" 
"developers/demos msm8953_64_N/platform/developers/demos" 
"developers/samples/android msm8953_64_N/platform/developers/samples/android" 
"development msm8953_64_N/platform/development" 
"docs/source.android.com msm8953_64_N/platform/docs/source.android.com" 

"libcore msm8953_64_N/platform/libcore" 
"libnativehelper msm8953_64_N/platform/libnativehelper" 
"ndk msm8953_64_N/platform/ndk" 

"pdk msm8953_64_N/platform/pdk" 
"platform_testing msm8953_64_N/platform/platform_testing" 

"sdk msm8953_64_N/platform/sdk" 

"tools/external/fat32lib msm8953_64_N/platform/tools/external/fat32lib" 
"tools/external/gradle msm8953_64_N/platform/tools/external/gradle" 
"tools/test/connectivity msm8953_64_N/platform/tools/test/connectivity"

"shortcut-fe msm8953_64_N/platform/vendor/qcom-opensource/shortcut-fe"
"toolchain/binutils msm8953_64_N/toolchain/binutils" 

"huaqin/overlay msm8953_64_N/huaqin/overlay" 
)

project_list=(
"${project_list_others[@]}"
"${project_list_vendor[@]}"
"${project_list_build[@]}"
"${project_list_system[@]}"
"${project_list_device[@]}"

"${project_list_external[@]}"
"${project_list_frameworks[@]}"
"${project_list_hardware[@]}"
"${project_list_packages[@]}"
"${project_list_prebuilts[@]}"
)

####################################################################
project_list_master_D2A=(
"packages/apps/Logapp msm8953_64_N/platform/packages/apps/Logapp"

"vendor/qcom/non-hlos-msm8953/MPSS.JO.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MPSS.JO.2.0"
"vendor/qcom/non-hlos-msm8953/MSM8917.LA.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8917.LA.2.0"
"vendor/qcom/non-hlos-msm8953/MSM8920.LA.1.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8920.LA.1.0"
"vendor/qcom/non-hlos-msm8953/MSM8937.LA.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8937.LA.2.0"
"vendor/qcom/non-hlos-msm8953/MSM8940.LA.2.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8940.LA.2.0"
"vendor/qcom/non-hlos-msm8953/RPM.BF.2.2 msm8953_64_N/platform/vendor/qcom/non-hlos/RPM.BF.2.2"
"vendor/qcom/non-hlos-msm8953/MPSS.JO.3.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MPSS.JO.3.0"
"vendor/qcom/non-hlos-msm8953/MSM8917.LA.3.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8917.LA.3.0"
"vendor/qcom/non-hlos-msm8953/MSM8937.LA.3.0 msm8953_64_N/platform/vendor/qcom/non-hlos/MSM8937.LA.3.0"

"vendor/huaqin/D2 msm8953_64_N/platform/vendor/huaqin/D2"
)
####################################################################

function git_clone()
{
    if [ $# -ne 2 ]; then
        echo "Error $*"
        exit 1
    fi
    local path_name=$1
    local remote_name=$2
	
	if [ -d "${path_name}" ]; then
		echo "======[PULL] ${path_name} ======"
		cd ${path_name}

		if [ -e ".git/index.lock" ]; then
		    rm -f .git/index.lock
		fi
		if [ ! -s ".git/ORIG_HEAD" ]; then
		    rm -f .git/ORIG_HEAD
		fi
		git rebase --abort
		git reset --hard
		git clean -df

		git pull `git remote` ${revision}
		cd -
	else
		if [[ ${path_name} =~ "/" ]]; then
			echo "======[CLONE] ${path_name%/*} ${path_name##*/} ======"
			mkdir -p ${path_name%/*}
			cd ${path_name%/*}
			git clone ${fetch_url}/${remote_name} -b ${revision} ${path_name##*/}
			cd -
		else
			echo "======[CLONE] ${path_name} ======"
			git clone ${fetch_url}/${remote_name} -b ${revision} ${path_name##*/}
			return 0
		fi
	fi
    
	echo ""
}



for i in "${project_list_master_D2A[@]}"
do
	echo "###### ${i} ######"
	git_clone $i
	sync
done